events {}

http {

    upstream cart_service {
        server cart-service:9090;
    }

    upstream stats_service {
        server stats-service:9091;
    }

    server {
        listen 80;

        # ---------------- CART SERVICE ----------------
        location /carts/ {
            proxy_pass http://cart_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # ---------------- STATS SERVICE ----------------
        location /stats {
            proxy_pass http://stats_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}